<?php    

echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/z4GCA/hash/bj5k72rc.css" />';
echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/z9NIK/hash/edbx0p1z.css" />';
echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/zE8KL/hash/168582wt.css" />';
echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/z7OLN/hash/85tbegc8.css" />';
echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/zBZF1/hash/cec4aw4x.css" />';
echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/zANRM/hash/s07b1wdi.css" />';
echo '<link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/z12XN/hash/5xqwlxtk.css" />';


?>
